# Generated by Django 6.0.5 on 2026-06-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_sale_price'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='product',
            name='product_price_positive',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0), ('price__lt', 9999999)), name='product_price_positive', violation_error_message='Ціна повинна бути від 0 до 9999999'),
        ),
    ]
