# Generated by Django 6.0.5 on 2026-06-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_product_price_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterConstraint(
            model_name='product',
            name='product_stock_positive',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='product_stock_positive', violation_error_message='Кількість товару повинна бути більше або дорівнювати 0'),
        ),
    ]
