# Generated by Django 6.0.5 on 2026-06-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_image_alter_product_product_stock_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/categories/'),
        ),
    ]
